### ISSUE TITLE
Corner transparency issue

### ISSUE THREAD

**Issue by Blazin64** [vinceliuice/Colloid-kde#3]
The KDE Plasma version of this theme seems to have a transparency issue on rounded corners. The GTK version is not affected.

KDE Plasma

![kde-corner](https://user-images.githubusercontent.com/26800120/165627441-b01745ec-2d07-40d6-959d-d639f806a87f.png)

KDE Plasma (from readme)

The issue is less visible in the readme screenshot, but you can see it if you zoom in.

![Screenshot_dark-corner](https://user-images.githubusercontent.com/26800120/165627451-de15ccd5-1f5a-4122-89cc-9ad8d44a3b64.png)

GTK

![gtk-corner](https://user-images.githubusercontent.com/26800120/165627435-8eee74d1-6c5b-4be9-bfe2-64a4ea17f80f.png)

**Comment by zeparu** [comment]
this is a long standing KDE Plasma bug with transparent corners with blur enabled

it may soon get fixed after being around for quite some time

if you want, you can try to search up "KDE Plasma Korner bug"

**Comment by Blazin64** [comment]
Oh, so the issue is with KDE Plasma and not the Colloid theme.

It looks like the fix should be applied in KDE Plasma 5.25, according to to the [bug report](https://bugs.kde.org/show_bug.cgi?id=395725). Bleeding-edge distributions like Arch Linux are already on 5.24.4, so that shouldn't be terribly far off! 😃
